/*Question 10 */
select name from client  order by name;

select deptno,max(salary)  from employee group by deptno;

SELECT DEPTNO,MIN(SALARY) FROM EMPLOYEE WHERE DEPTNO!='D001' GROUP BY DEPTNO;

/*Question 11*/

SELECT column_name(s) FROM table1 UNION SELECT column_name(s) FROM table2;

SELECT DEPTNO FROM EMPLOYEE UNION SELECT DEPTNO FROM DEPT;

SELECT DEPTNO FROM EMPLOYEE MINUS  SELECT DEPTNO FROM DEPT;

SELECT EMPNAME FROM EMPLOYEE  WHERE SALARY >(SELECT SALARY FROM EMPLOYEE  WHERE EMPNAME='Adarsh');

SELECT EMPNAME  FROM EMPLOYEE  WHERE SALARY < (SELECT MIN(SALARY)  FROM EMPLOYEE  WHERE DEPTNO='D004');

SELECT EMPNAME,SALARY  FROM EMPLOYEE  WHERE SALARY >  (SELECT MIN(SALARY)  FROM EMPLOYEE  WHERE JOB LIKE'A%');

SELECT *  FROM EMPLOYEE,DEPT WHERE EMPLOYEE.DEPTNO=DEPT.DEPTNO;

SELECT * FROM EMPLOYEE,DEPT WHERE EMPLOYEE.DEPTNO!=DEPT.DEPTNO;


SELECT EMPNAME,JOB,MANAGER
FROM EMPLOYEE
LEFT JOIN DEPT ON EMPLOYEE.DEPTNO=DEPT.DEPTNO;

SELECT EMPNAME,JOB,MANAGER
FROM EMPLOYEE
RIGHT JOIN DEPT ON EMPLOYEE.DEPTNO=DEPT.DEPTNO;

SELECT EMPNAME,JOB,MANAGER
FROM EMPLOYEE
FULL OUTER JOIN DEPT ON EMPLOYEE.DEPTNO=DEPT.DEPTNO;
